### ISSUE TITLE
Formatting yaml is buggy

### ISSUE THREAD

**Issue by brbzull0** [brbzull0/rpc_client#1]
When using `-f yaml` and printing a jsonrpc `Request` object we get metadata printer when converting the object to a yaml string.

```
tscli -f yaml config --get proxy.config.diags.debug.tags
```

```
-->
{}
!!python/object/new:ts_jsonrpc.jsonrpc.jsonrpc.JsonRpcMessages.Request
dictitems:
    id: 4dc8839c-f9a2-11ea-8ede-001fc69cc946
    jsonrpc: '2.0'
    method: admin_config_get_records
    params:
    - proxy.config.diags.debug.tags

<--
id: 4dc8839c-f9a2-11ea-8ede-001fc69cc946
jsonrpc: '2.0'
result:
-   access: '0'
    checktype: '0'
    current_value: test_tag
    data_type: STRING
    default_value: http|dns
    name: proxy.config.diags.debug.tags
    order: '421'
    overridable: 'no'
    raw_stat_block: '0'
    record_class: '1'
    record_type: '3'
    source: '1'
    syntax_check: 'null'
    update_status: '1'
    update_type: '1'
    version: '0'
```
this should not be printed:

```
{}
!!python/object/new:ts_jsonrpc.jsonrpc.jsonrpc.JsonRpcMessages.Request
dictitems:
```
